modLoader="javafml" #mandatory
loaderVersion="[40,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.
license="MIT License"
[[mods]]
modId="resourceslimes" #mandatory
version="0.2.13-1.18.2" #mandatory
displayName="Resource Slimes" #mandatory
logoFile="resource_slimes_logo.png" #optional
credits="Thanks to my awesome Community for all the support <3" #optional
authors="Kaupenjoe" #optional
description=''' WIP '''

[[dependencies.resourceslimes]] #optional
    modId="forge" #mandatory
    # Does this dependency have to exist - if not, ordering below must be specified
    mandatory=true #mandatory
    # The version range of the dependency
    versionRange="[40,)" #mandatory
    # An ordering relationship for the dependency - BEFORE or AFTER required if the relationship is not mandatory
    ordering="NONE"
    # Side this dependency is applied on - BOTH, CLIENT or SERVER
    side="BOTH"

[[dependencies.resourceslimes]]
    modId="minecraft"
    mandatory=true
# This version range declares a minimum of the current minecraft version up to but not including the next major version
    versionRange="[1.19,1.20)"
    ordering="NONE"
    side="BOTH"
